# Generated by Django 6.0.7 on 2026-08-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalbanner',
            name='link_url',
        ),
        migrations.AddField(
            model_name='festivalbanner',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='festivalbanner',
            name='image',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
