# Generated by Django 6.0.7 on 2026-08-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, help_text="Small square/circular icon used in the homepage 'Shop by Category' row. Falls back to the banner image if left blank.", null=True, upload_to='categories/icons/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner image used on the category grid page and category detail header.', null=True, upload_to='categories/'),
        ),
    ]
