# Generated by Django 6.0.7 on 2026-08-01 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_festivalbanner_link_url_festivalbanner_slug_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='festival_collection',
            field=models.ForeignKey(blank=True, help_text='Select if this product belongs to a specific festival collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='homepage.festivalbanner'),
        ),
    ]
